apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs
  namespace: storage
  labels:
    app: nfs
spec:
  storageClassName: ebs-sc
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi