apiVersion: batch/v1
kind: CronJob
metadata:
  name: mysql-backup
spec:
  schedule: "*/10 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: awscli
            image: ibrareurus3344/mysqlrestore
            env:
            - name: AWS_ACCESS_KEY_ID
              value : <access key>
            - name: AWS_SECRET_ACCESS_KEY
              value : <secret accesskey>
            - name: AWS_REGION
              value: us-west-2
            - name : BUCKET_NAME
              value : mysql-backup-from-eks
            volumeMounts:
            - name: persistent-storage
              mountPath: /var/lib/mysql
          volumes:
          - name: persistent-storage
            persistentVolumeClaim:
              claimName: mysql-pv-claim
          restartPolicy: OnFailure