apiVersion: batch/v1
kind: CronJob
metadata:
  name: s3-backup-db
spec:
  schedule: "*/10 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: s3-access-and-ssm
          # activeDeadlineSeconds: 7200
          containers:
          - name: init-s3
            image: amazon/aws-cli
            command:
                - bash
                - "-c"
                - |
                  #!/bin/sh
                  set -o pipefails
                  yum -y update && yum install -y tar && yum install -y gzip
                  d=$(date +"%d-%m-%y")
                  t=$(date +"%T")
                  name="mysql"
                  newt=$(echo $t | sed 's/:/-/g')
                  cd /var/lib 
                  tar -zcvf  bkup.tar.gz mysql/* 
                  ls -lh
                  aws s3 cp bkup.tar.gz s3://mysql-backup-from-eks/"mysql$t"
                  echo "ending"
            volumeMounts:
            - name: data
              mountPath: /var/lib/mysql
          volumes:
          - name: data
            persistentVolumeClaim:
              claimName: mysql-pv-claim
          restartPolicy: Never 