# ---
# apiVersion: rbac.authorization.k8s.io/v1
# kind: Role
# metadata:
#   name: reader
#   namespace: dev
# rules:
# - apiGroups:
#   - "*"
#   resources: ["deployments", "configmaps", "secrets", "services"]
#   verbs: ["get", "list", "watch"]
# ---
# apiVersion: rbac.authorization.k8s.io/v1
# kind: RoleBinding
# metadata:
#   name: reader
#   namespace: dev
# subjects:
# - kind: User
#   name: syed.shadab
#   apiGroup: rbac.authorization.k8s.io
# roleRef:
#   kind: Role
#   name: reader
#   apiGroup: rbac.authorization.k8s.io

--- 
# https://kubernetes.io/docs/reference/access-authn-authz/rbac/
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: reader
  namespace: dev
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["pods"]
  verbs: ["get", "watch", "list"]
---

# https://kubernetes.io/docs/reference/access-authn-authz/rbac/
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: rolebinding
  namespace: dev
subjects:
- kind: Group
  name: reader # Name is case sensitive
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: reader
  apiGroup: rbac.authorization.k8s.io
---
