apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: nginx-deployment-spc-k8s-secrets
spec:
  provider: aws
  parameters: 
    objects: |
      - objectName: "DBSecret_edge_deployment"
        objectType: "secretsmanager"
        jmesPath:
          - path: password
            objectAlias: dbpassword
  secretObjects:                
    - secretName: my-secret-01
      type: Opaque
      data:
        - objectName: dbpassword
          key: db_password_01